#!/bin/bash

# Script for running all the project tests. On success it returns 0. On the
# failure of any test it returns 1.

# TODO: A Windows version of this script.

# Ensure current directory is the directory this script lives in.
pushd $(dirname $0) >/dev/null

find . -nowarn \
       -mindepth 2 -and \
       -maxdepth 2 -and \
       ! -iname '*.pyc' -and \
       ! -path './.*' -and \
       -type f -and \
       -executable -and \
       ! -exec {} \; -and \
       -exec echo "FAILED: {}" 1>&2 \; -and \
       -exec touch failure-indicator  \;

if [ -e failure-indicator ]; then
    rm failure-indicator
    popd >/dev/null
    exit 1
else
    popd >/dev/null
    exit 0
fi
