#!/bin/bash

# Script for running all the project tests. On success it returns 0. On the
# failure of any test it returns 1.

# TODO: A Windows version of this script.

find . -nowarn \
       -mindepth 2 -and \
       -maxdepth 2 -and \
       ! -iname '*.pyc' -and \
       ! -path './.*' -and \
       -type f -and \
       -executable -and \
       ! -exec {} \; \
       -exec touch failure-indicator  \;

if [ -e failure-indicator ]; then
    rm failure-indicator
    exit 1
else
    exit 0
fi
